apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgAcfonN1xWYL4wrNU2ysHlWTriQeSyVvL/cAZ3vCz3H2lVn6/wkqPPELbf/yqtTDo/2Zyql35EFSsYTvnMm9V/h5vC1YL6zewuKTx9XLaEk53yZ/zbq039eT+98fhq3uxYsvEwOMO+jwhZyHhDiTCXvpDDDnzmDglVVU7SPko8EZ2w2lx8DCMmVV3eM49cgsL9oixuBUpOMoD4MJEcAQ0u3bQnSgs6yphqezKeSVX8o40MjGiUUkGy+wnIjrweo4DYop2RryIiGntQtjJ7RMIT8r+8Ygy79wbNbfCwFsBTTm9i6+gd3ahkHhX8SxC1D0TvL9ODjimnXwpPfysIrj13/i607wbsNuL5/u1GGMVJUkNknfFGdW9306JYnsxAp7eum2fLgqdQZoMqpDEhhgyFhwadu8RhtM87TF4vaf1d3HS4Ej53T5r2L1MfNv442oedA1saRMYy4bRHGG4ut/8tx7U/6FByUCOjr5gdtyhqVZOxfSk4cSqh2oqX/AWtEdYC7u5UImvvTSpm59dZpfVfR4UWb4v+SdY91j1FNLgwmbPQk0cE5uFuYv4M2s3yZ2CRmPi43b3+d2++WYn2pA+g2qfwrr/6NZSzOVP8OeLuK2WjGV8HDKpONT0AWLoEfTzIVu69kA3JZHMjK981dLC0f+ucyp42dZiQmG4rqcYf+hD4oW8ecZ2C+Qe9+ackb9qV+yG2L6ac0GZUtiwwbinEXW5idJC0qi0nAGjU0yeF2gVClcpYyCGlSr9uIHy5YNs2Y+eGB+pBVJCS85sxYxOsFOIUdAFkXvFTfVKP6kMG/5XW6jiFhg9u1h1Qz/wPY19TWJTI8nvHjGbwRsgjrA9nyzRO1kCtw9BWcxtYj2SFZ6X33IJnvS4YN3fA85pEMlJr1Da2CzIsjRmH719dTOzK4h8N+bYNAhNRe2FhNpsM2fApgXs0=
  template:
    metadata:
      name: ghcr-secret
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson
