apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-proxy-config
  namespace: kube-system
spec:
  encryptedData:
    trusted-ips: AgCwbyEpI4FuY/hxhgK3xWyMhmEXWwXSjRA2eEdbLLnu6c1BtR20JfOdM+LClwG47mUnAN/D2iCqNLzhc2YkAMb5Xbxhi6B7d5Wdx4u0rGZUsVlJq+sGJxlgR2lbMdkOfnpiq5ecDNu2M9SJNGbZEzMSqGlUfAHl2Kd9c/XGjyfO2FPb+bt00mkWgsu1NL1VORcSKma9B69MzpLPT4L3AlO4YUqKzGquETxA3zCH+7inNpxnNISQ9ICfgQfFZXdMbZ7o1h+H0C4uPl0SCmjZP8ehMUTG7IHKxGz0Ha1utgSnn2F6G6yv3ZMD9yFnr5rCP/4ccbXf+/DqaE82CpIou/iNj2CgfbyUIYKuccEdkjAQrQqWmDMKDxSr7deJ9NpvsIYiJiP46hbLHMI1SLpzpqZVmaeonBRjn/sBJgJDjpDcY2LvBacmphkQR/gWTddJ+KElffmGCZuu93q9akhFcmxR6MgamYDv2VYJqbEeL/8APkyDCkLJl3TGbDW3u1xlwOoxm2C6krqabD0IuECJGUo3K1fhQ4XLY57qLKLZRCTJhDjTn1HTiK9l6D+vQmSucbU2MW82hcnuN/ze2W3Cd2LPxJGueGrTSdVPmQluOPEEgPH7B/DQBBpGrymTPJISMPqh0V+ZMigZgpvJRjIH8/0mkfkZ7w7ZPylRS1l0wnCDVlmjwC9HIWkQ38aPodZ2JfBn1XnKCJ9q2bgptqrTlQ==
  template:
    metadata:
      name: traefik-proxy-config
      namespace: kube-system
    type: Opaque
