apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/megisholavonat/gitops.git
    targetRevision: HEAD
    path: cluster/apps
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
