apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mhav-dev-basic-auth
  namespace: mhav-dev
spec:
  encryptedData:
    users: AgCNT4u7u8eEMZ0QjZj8xUWusy2CRI7KF5gmfcg56yxhjNceFm4pzXwl07XvDJfX58SG5oswCyvd6k6LSJytuFuqgFv2Ag3FSGDdVD0KNcpyajONnO/FCJzaUjZ+qk58uq70DgQCc3XXbZrnN4utTjZRkf/J0XDrUJowpCgXvMXbIKKqlAKnbCSnAzq9EsgLO3HiLICx1f8VOdsCTDnKjEczDYc5BDUI7cXy0qHZwy7PAV/mfyh82wrjmnAipRBFVMLe/AIM7WlB87EnHe+eHH1NJR7WttmbnAyEJqXI12/xsCySnO7S2SSJE/10CY9PHBJEHi9ia8nWOsfV91TdcnmWdUHSHbN/zo7l+jZLO4qiQ6gnHi4uZIo6wLw8ZY5emlRss63iFyHKDwhGKzEIa90NW/+82h/1GhGlpdbXikr6sGRH1CwwLHrBSRkP6fVWUGbqF/1Oep+3u84M8PIlAOkGQ7WFMLJQQgfZX+YYaRW6CUy+vf5uzcTN1azUUgXEHktxQVgE3CR5T9nSoSG1wzZDkePaGBWjol6eiXmIOEXScRzSbq8WZV3BB6JSMgnnEwn/RKw6BbtY0Syc1pnf6UlGgcCyBv4YkDNEDSWIEOopQ46XVry7N+mgUbLeCYS4Hs6GE+cHNO/zMhZvO8TALue378cKfJeTpiCRUBRkCVhta16SqIaX7H5JOSQrOr04DrEkdHPavBhF0PpCm+HN0CNTr3VS2az36nCYnElGMVUG/aocrTrVNUBnOuQG
  template:
    metadata:
      name: mhav-dev-basic-auth
      namespace: mhav-dev
    type: Opaque