---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAQi8qWtYBnkDSXmd0lGQrVdFczXvmFtgcLWEHgv77oCEBMw7GqM5L8RFVz2KMkF9wCKW+bVj97Ik/F9Rqb19sqTK7pnNsPBOYFHcED37DFENJ2g+gkceip/6KXEJ3adCUKmZ3WvvnkWgsguh4i7Nnd0FJ+9gf1odHn+qApEXHf7mxM+32+Ub5UbP2w3pwJnKGLjbCNdkb8q9bQgrDseljIq7sfHN+/2Ih9UhDihM9/ZB0xpjV96Ajt0IRkaRffTtUcdWwCMpc80u5JqTN2rp+rFD7WgzFdVH0PefLGwoA+l3j6ZbDjjVJzvaNovAw9aC5ES/QJmRFhLbHpEKBYx3qzWjrukGnuyxrn5okIEtY2zja6llGdxp1Ci06iBDemIUD/8zOTR3iKJOZWFMnbPs3AN15fFMig54HQ0BDZaEh9WcQbbhO1Jo+1aaDIZXOlFkP9pd171nC+QmXvTNbNLC++LOWGppFPmavgI4antiSKUSBZfsUWPLBF6EIrxxMOytJlk6ulQKAp6VP1QvVZcdQGdgLBCL9jzQ8jyP47W2pJkRE34DNhlvFvcy2SVT7MmxObLvedd6lhkfYXfS64+opQLuypkWl7vgGZzkg4kTPWUQI8Ttp5nVxznc4+Wdvgi47ITQxDpqmPRlDTluSc12W6LVEC25oWHP+ZnSUN9L+mVQdQuwbtTsXTUYP8cTxO0XglnaHu5bfvHKweJKeJcmhrwvjCVnvQyUt97fgVQgdGnWBqfbfmnjbNUSOttKshmnFw3eS7uBnL7Qx+IwDschayhLJuOOOOk9UZt+HoEVGrCqzZX8po+5XTJg8Cx7l7eG7vflkjiBHWD586bnoBgoEGGDcdjRpk6jACZEuQQvT/1NydKzrL/Z6GmTV8PrCnSszJx8b4ZWfWIa/HzN3V3o96bLNq+08GxoM1tNCbgxSI7uwlmm0=
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
