apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mhav
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/megisholavonat/gitops.git
      targetRevision: HEAD
      path: cluster/apps/mhav
  destination:
    name: in-cluster
    namespace: mhav
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true