apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mhav-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/megisholavonat/gitops.git
      targetRevision: HEAD
      path: cluster/apps/mhav
      helm:
        valueFiles:
          - values-dev.yaml
  destination:
    name: in-cluster
    namespace: mhav-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
