apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/cloudpirates
      chart: redis
      targetRevision: 0.13.x
      helm:
        valueFiles:
          - $values/cluster/data/redis/values.yaml
    - repoURL: git@github.com/megisholavonat/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true